-- Setup database and table for mortgage lending demo data
-- Created by Cortex Code

-- Create database
CREATE DATABASE IF NOT EXISTS COCO_DEMO;

-- Create table
CREATE OR REPLACE TABLE COCO_DEMO.PUBLIC.MORTGAGE_LENDING_DEMO_DATA (
    LOAN_ID NUMBER,
    TS TIMESTAMP_NTZ,
    LOAN_TYPE_NAME VARCHAR(50),
    LOAN_PURPOSE_NAME VARCHAR(50),
    APPLICANT_INCOME_000S FLOAT,
    LOAN_AMOUNT_000S NUMBER,
    COUNTY_NAME VARCHAR(100),
    MORTGAGERESPONSE NUMBER
);

-- Create stage for CSV upload
CREATE OR REPLACE STAGE COCO_DEMO.PUBLIC.MORTGAGE_STAGE 
FILE_FORMAT = (
    TYPE = 'CSV' 
    SKIP_HEADER = 1 
    FIELD_OPTIONALLY_ENCLOSED_BY = '"' 
    NULL_IF = ('')
);
