-- Analysis queries for mortgage lending demo data

-- Overall statistics
SELECT 
    COUNT(*) AS total_loans,
    SUM(CASE WHEN MORTGAGERESPONSE = 1 THEN 1 ELSE 0 END) AS approved,
    SUM(CASE WHEN MORTGAGERESPONSE = 0 THEN 1 ELSE 0 END) AS denied,
    ROUND(AVG(CASE WHEN MORTGAGERESPONSE = 1 THEN 1 ELSE 0 END) * 100, 2) AS approval_rate_pct,
    ROUND(AVG(APPLICANT_INCOME_000S), 2) AS avg_income_000s,
    ROUND(AVG(LOAN_AMOUNT_000S), 2) AS avg_loan_000s
FROM COCO_DEMO.PUBLIC.MORTGAGE_LENDING_DEMO_DATA;

-- Top 10 counties by loan volume
SELECT 
    COUNTY_NAME,
    COUNT(*) AS loan_count,
    ROUND(AVG(LOAN_AMOUNT_000S), 2) AS avg_loan_000s
FROM COCO_DEMO.PUBLIC.MORTGAGE_LENDING_DEMO_DATA
GROUP BY COUNTY_NAME
ORDER BY loan_count DESC
LIMIT 10;

-- Breakdown by loan type
SELECT 
    LOAN_TYPE_NAME,
    COUNT(*) AS count,
    ROUND(AVG(CASE WHEN MORTGAGERESPONSE = 1 THEN 1 ELSE 0 END) * 100, 2) AS approval_rate_pct
FROM COCO_DEMO.PUBLIC.MORTGAGE_LENDING_DEMO_DATA
GROUP BY LOAN_TYPE_NAME
ORDER BY count DESC;

-- Breakdown by loan purpose
SELECT 
    LOAN_PURPOSE_NAME,
    COUNT(*) AS count,
    ROUND(AVG(LOAN_AMOUNT_000S), 2) AS avg_loan_000s,
    ROUND(AVG(CASE WHEN MORTGAGERESPONSE = 1 THEN 1 ELSE 0 END) * 100, 2) AS approval_rate_pct
FROM COCO_DEMO.PUBLIC.MORTGAGE_LENDING_DEMO_DATA
GROUP BY LOAN_PURPOSE_NAME
ORDER BY count DESC;
